"""empty message

Revision ID: 7cc31f8ef0e5
Revises: 3ad435d4ed79
Create Date: 2021-08-19 19:22:18.103133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc31f8ef0e5'
down_revision = '3ad435d4ed79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('img_path', sa.String(), nullable=False))
    op.drop_column('movie', 'imgPath')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('imgPath', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('movie', 'img_path')
    # ### end Alembic commands ###
