"""empty message

Revision ID: 879ad76ae52e
Revises: 7d452c649811
Create Date: 2021-08-21 13:57:01.859000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879ad76ae52e'
down_revision = '7d452c649811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('all_rates_count', sa.Integer(), nullable=False))
    op.add_column('movie', sa.Column('all_rates_total', sa.Integer(), nullable=False))
    op.drop_column('movie', 'rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('movie', 'all_rates_total')
    op.drop_column('movie', 'all_rates_count')
    # ### end Alembic commands ###
